### ISSUE TITLE
翻译对照表

### ISSUE THREAD

**Issue by olOwOlo** [illyasviel/crowds#12]
| 原文        | 翻译    | 备注 |
| :--------:   | :-----:   | :----: |
| crowds  | 群体 | #2 讨论 |
| madness  | 愚蠢 | #2 讨论 |
| wisdom   | 智慧 | #2 讨论 |
| contagions | 传播 | #4 讨论，[复杂网络理论及其应用](https://books.google.com/books?id=IMzxW0XiuDQC&pg=PA81&lpg=PA81&dq=%E5%A4%8D%E6%9D%82%E4%BC%A0%E6%92%AD&source=bl&ots=fwe-djFlJB&sig=GaDonEtGLUDjev-EK-rp8KIzeWA&hl=zh-CN&sa=X&ved=2ahUKEwizwbW_x-baAhUI8WMKHTTIACA4ChDoATADegQIABA7#v=onepage&q=%E5%A4%8D%E6%9D%82%E4%BC%A0%E6%92%AD&f=false) |
| contagion threshold | 传播临界值 | 同上 |
| spread | 扩散，蔓延等 | 为了避免与 contagion 的冲突 |
| Small World Network | 小世界网络 | [wiki](https://zh.wikipedia.org/wiki/%E5%B0%8F%E4%B8%96%E7%95%8C%E7%B6%B2%E8%B7%AF) |
| groupthink | 团体迷思 | [wiki](https://zh.wikipedia.org/wiki/%E5%9C%98%E9%AB%94%E8%BF%B7%E6%80%9D) |
| bonding social capital | 内聚型社会资本 | #7 讨论 |
| bridging social capital | 桥接型社会资本 | #7 讨论 |
| bonding | 内聚 | #7 讨论 |
| bridging | 桥接 | #7 讨论 |
| sweet spot | 最佳状态 | #7 讨论 |
| idea | 思想 | 在此讨论 |

有些词并不是一定要一一对应的，意译比直译更好的情况下，当然随意啦~

**Comment by olOwOlo** [comment]
**idea**
- 想法？
- 思想？
- 不需要统一？

**Comment by lxdlam** [comment]
我的翻译暂时是【想法】，conclusion部分提到了belief，那么如果考虑这两个词的联系我认为【思想】可能更好。

**Comment by appleseed0910** [comment]
idea这种词我觉得不太需要统一，看前后文语境，毕竟即使是在这个project里面它也不是一个特殊词，就是泛指想法和点子或者看法思维之类的…翻到的时候确保一句话念起来顺口并且意思无误就可以了吧？
