### ISSUE TITLE
调整文字排版

### ISSUE THREAD

**Issue by antfu** [illyasviel/crowds#17]
https://github.com/illyasviel/crowds/blob/fb2e7c95255f35283774ef86410d209bddb97d25/index.html#L306-L314

目前在 `zh-CN` branch 上我 Chrome v66.0.3359 (Windows 10) 渲染如下

![image](https://user-images.githubusercontent.com/11247099/39625653-ef88b4d2-4fd0-11e8-93c3-3a0e9108fa08.png)

**Comment by olOwOlo** [comment]
嗯，我知道的，之后会改的

**Comment by olOwOlo** [comment]
正在改
