### ISSUE TITLE
最后

### ISSUE THREAD

**Issue by olOwOlo** [illyasviel/crowds#18]
预览：[看这里](https://rawgit.com/illyasviel/crowds/zh-CN/zh-CN.html)
文件对比 / 校对：[这里](https://github.com/illyasviel/crowds/compare/0df9f09c394a544c93828ac8a92b63cac77fec18...illyasviel:c61e883e2a09d3ac9e5ca97bebd962fe94142bca)
发现问题留言或者直接 PR

等作者收了之前的 PR 就推送该翻译

以及，麻烦说以下你们需要署的名 @appleseed0910 @5thgfka @lxdlam @antfu

**Comment by lxdlam** [comment]
哇 辛苦啦～
我都没问题的 就lxdlam就好

**Comment by appleseed0910** [comment]
各位辛苦了！！（总是关键时刻消失的我
第一次在github上完成合作项目 _(:з)∠)_ 弄出了不少问题 感谢各位担待（特别是host小哥哥XDD
我的署名请用 foxiee
谢啦！

**Comment by antfu** [comment]
大家辛苦了！
我 antfu 就好，感谢了。

**Comment by 5thgfka** [comment]
各位辛苦了！
第一次在 github 上完成合作项目。哈哈
我的署名就用 ekse 吧。
谢谢！
