### ISSUE TITLE
关于标题应该怎么翻译

### ISSUE THREAD

**Issue by olOwOlo** [illyasviel/crowds#2]
The Wisdom and/or Madness of Crowds

Wisdom，Madness，Crowds 这几个词贯穿整个游戏了，直译总感觉少了点什么= =

**Comment by appleseed0910** [comment]
正在翻bonus，第一条就是the wisdom of crowds
说一下我的个人看法，James Surowiecki这本书不管是大陆还是湾湾通俗名称好像都是《群体的智慧》
我在翻reference的时候心里给这几个词组排列组合的暂用名是
群众之智/群众之愚
很直白的了，才疏学浅抛砖引玉啦XD

**Comment by lxdlam** [comment]
大陆的译名其实有一个叫《百万大决定》，实在不知道内在联系
我觉得crowds更多强调的是“群”这个概念，我个人倾向于【群体】

**Comment by 5thgfka** [comment]
乌合之众 the crowded

**Comment by olOwOlo** [comment]
先确定一下这三个词在下文应该怎么翻译吧~

---

说一下我的提议（只是提议）：

| Wisdom| Madness | Crowds |
| :-: | :-: | :-: |
| 智慧 | 愚蠢 | 群体 |

Madness 这个词既有“愚蠢”，又有“疯狂”的意思，或许可以像[appleseed0910这样](https://github.com/illyasviel/crowds/pull/10/files#diff-a24cad334377da6f64bfd1bb2d7ecdcaR1065)在适当的情况把两个意思都写上？_“愚蠢” 还是 “愚昧”？_

---

干完了，再决定

- 标题：The Wisdom and/or Madness of Crowds
- 描述：an interactive guide to human networks
- 分享描述：Why do groups of people act smart, dumb, kind, cruel? An interactive guide to human networks:

怎么翻译吧

**Comment by olOwOlo** [comment]
@5thgfka “乌合之众” 以偏概全了，wisdom 都被丢弃了 😭

**Comment by lxdlam** [comment]
@olOwOlo 我感觉madness在游戏中没有特别的强调疯狂这个含义，更多的是作为【智慧】的对立面，所以【愚蠢】可能更好

**Comment by olOwOlo** [comment]
@lxdlam 也不能说没有强调，愚蠢和疯狂也有点相关性，我的意思是因为这个词的多义性，可以在措辞合理的情况把疯狂加上去，当然主要意思仍然是愚蠢
